### ISSUE TITLE
Error when picking a herb

### ISSUE THREAD

**Issue by sWxJaPkT** [theoden-dd/gatherer_p2p#6]
https://i.imgur.com/6C2v9li.png

**Comment by theoden-dd** [comment]
Thank you for the feedback.

Please, name the branch or commit you have used to test.

Actually I haven't released the addon yet. Just preparing a pull request to jsb repo at the moment.

**Comment by theoden-dd** [comment]
And one more crucial question: any localizations on the client?

**Comment by sWxJaPkT** [comment]
Oh srry - uhhh.. i just downloaded the latest version from https://github.com/theoden-dd/gatherer_p2p/

Latest commit 851586b

No localizations

**Comment by theoden-dd** [comment]
I've looked through the code. Error happened on "start casting" event. It seems addon was unable to extract the herb name from a tooltip.

So you tried to pick up a herb. What herb it was? In which location? Any custom frames like Luna or X-Perl?

Also please provide a list of addons that modify mouseover tooltip at the right bottom corner or turn them off while testing.

I recommend you to use the version I suggested as a pull request: https://github.com/theoden-dd/gatherer_p2p/archive/release/1.0.0.zip . However, my changes don't address the discussed error.

Code note for me:
```lua
	-- process tooltips text for 1.12
	elseif ( event == "SPELLCAST_START" ) then
		if ( arg1 and (arg1 == GATHER_HERBALISM or arg1 == TRADE_MINING or arg1 == TRADE_OPENING or arg1 =="") ) then
			Gatherer_Debug("|cffffffffEvent :|r "..event.." => "..arg1);
			Gatherer_currentNode = GameTooltipTextLeft1:GetText();
			Gatherer_currentAction = arg1;

			Gatherer_Debug("Current node: "..Gatherer_currentNode); -- here was the nil value concatenation
			Gatherer_RecordFlag=1;
		end
```
