### ISSUE TITLE
Duplicate exclusion after random selection

### ISSUE THREAD

**Issue by theoden-dd** [theoden-dd/gatherer_p2p#7]
Introduce a local (**to a game session**) table - lightweight mirror of the GatherItems.

It will keep just one flag for now: `isDuplicate -- type: bool`.

When adding to the db a node, which is a duplicate,
entry with the flag equal to true will be added to the table.
Addressing stays the same: [continent][zone]... etc. same keys.

After selecting random node add a check if the found node is a duplicate.
If yes, skip broadcasting.

Strategically this leads to one unique broadcaster of the single node on the net.

**Comment by jsb** [comment]
Sounds generally like a good idea but what happens after the "original" broadcaster (player X) goes offline? The remaining players will have X's nodes marked as duplicates, hence nobody will be sharing them anymore.

I guess this is less of a problem with many other players going online and offline in between but I would suggest to only keep the "duplicate" status as a per-session variable so it will eventually recover from such inconsistencies.

**Comment by theoden-dd** [comment]
> Introduce a local (**to session**) table

Well, you're absolutely right. It'll be session wide. So any new logged in person will have empty duplicates table and start broadcasting all (s)he has.

It seems I should have to emphasize it more.
